### ISSUE TITLE
-watch option does not work on MacOS

### ISSUE THREAD

**Issue by akubiczek** [irmen/prog8#20]
Hi Irmen!

When trying to use the option -watch on MacOS (Big Sur v 11.0.1), i.e:

`java -jar prog8compiler-5.0-all.jar -target cx16 -watch test.p8`

it gives me a result:

```
Imported files (now watching:)
  test.p8
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.register(java.nio.file.WatchService, java.nio.file.WatchEvent$Kind[])" because the return value of "java.nio.file.Path.getParent()" is null
	at prog8.CompilerMainKt.compileMain(CompilerMain.kt:71)
	at prog8.CompilerMainKt.main(CompilerMain.kt:21)
```

Java version:

```
java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```

**Comment by irmen** [comment]
I'm sorry I can't debug this as I don't have MacOS.

Can you try it with another JDK version, such as 1.8 or 11?   (those are the ones I use with Linux)

**Comment by akubiczek** [comment]
Yeah, the workaround works on Mac too :) Thanks.

**Comment by irmen** [comment]
release 5.1 is now available that contains this fix (and many optimizations)
