### ISSUE TITLE
NullPointerException when assigning string literal to byte array

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#34]
* **Prog8 version**: 6.4
* **Command**: `java -jar prog8compiler-6.4-all.jar prog8-issue34.p8`
* **Source code**:
```
%import textio
%zeropage basicsafe
%option no_sysinit

main {
	byte[] xs = "foo" ; <<<<<<<<<<<<
	sub start() {
		txt.print(xs)
	}
}
```
* **Expected**: type error being reported
* **Actual**:
```
* internal error *
Exception in thread "main" java.lang.NullPointerException
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:631)
        at prog8.ast.statements.VarDecl.accept(AstStatements.kt:242)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:30)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:182)
        at prog8.ast.statements.Block.accept(AstStatements.kt:66)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:14)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:48)
        at prog8.ast.Module.accept(AstToplevel.kt:365)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:10)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:44)
        at prog8.compiler.astprocessing.AstExtensionsKt.checkValid(AstExtensions.kt:14)
        at prog8.compiler.CompilerKt.processAst(Compiler.kt:257)
        at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:97)
        at prog8.CompilerMainKt.compileMain(CompilerMain.kt:106)
        at prog8.CompilerMainKt.main(CompilerMain.kt:23)
```
* **Remarks**:
  - I've never worked with Kotlin, so please bear with me :)
  - In [`AstChecker.kt`](../blob/v6.4/compiler/src/prog8/compiler/astprocessing/AstChecker.kt), there's the private fun `checkValueTypeAndRangeString(...) : Boolean` called from inside `visit(...)`. It seems the return value is not used.
  - The above link points to the v6.4 source file, ie. line numbers from the trace refer to this rev.

**Comment by irmen** [comment]
Thanks for the clear bug report!

**Comment by meisl** [comment]
Pretty fast fix :)
I haven't yet gotten around to setting things up for building prog8 myself (and familiarizing myself with the code).
I saw the changes to [`examples/test.p8`](dae59238cd3b) - maybe also an extra unit test for this?

**Comment by irmen** [comment]
I’m using that file as a scratch file to test stuff , I guess it shouldn’t have been put into git. 

Adding more unit tests is something I wish to do but lack the time for atm
