### ISSUE TITLE
Exception/Error thrown on various escape sequences in str literals, depending on encoding

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#37]
* **Prog8 version**: 6.4
* **Command line**: java -jar prog8compiler-6.4-all.jar prog8_issue37.p8
* **Source code**:
	```
		%import textio ; txt.*
		main {
			sub start() {
				; ATTENTION: uncomment only one problematic line at a time!
			
				; Normal string literals, i.e. PETSCII encoding
				; ---------------------------------------------
				txt.print("\"")	; fine
				txt.print("\n")	; fine
				txt.print("\r")	; fine
				; txt.print("\\")	; yields CharConversionException
				; txt.print("xyz\\")	; yields prog8.compiler.AssemblyError
			
				; @-strings, i.e. translated into 
				; the alternate character encoding (Screencodes/pokes)
				; ----------------------------------------------------
				txt.print(@"\"")	; fine
				txt.print(@"\n")	; yields CharConversionException
				; txt.print(@"xyz\n")	; yields prog8.compiler.AssemblyError
				; txt.print(@"\r")	; yields CharConversionException
				; txt.print(@"xyz\r")	; yields prog8.compiler.AssemblyError
				; txt.print(@"\\")	; yields CharConversionException
				; txt.print(@"\\")	; yields prog8.compiler.AssemblyError
				
				; there may be more...
			}
		}
	```
* **Expected**:
  - regular error message, including src location in user program
  - also: the problematic character should be shown in escaped form, eg: "\n" rather than an actual new line in the output
* **Actual**: exception thrown
  - either `CharConversionException` in the case of one-letter only strings (eg `@"\\"`, `"\\"`)
  - or `prog8.compiler.AssemblyError` in the case of longer strings  (eg `@"xyz\\"`, `"xyz\\"`)
  - *ATTENTION*: **uncomment only one problematic line at a time!**
    You will otherwise get very quickly confused which error is caused by which line (reason: happen in completely different phases).
  - shown below are the faults for the `@"\n"` and `@"xyz\n"` cases; the others are similar
	```
		* internal error *
		Exception in thread "main" java.io.CharConversionException: no lowerScreencode character for '
		' (10)
				at prog8.compiler.target.c64.Petscii.encodeScreencode(Petscii.kt:1088)
				at prog8.compiler.target.Cx16Target.encodeString(ICompilationTarget.kt:92)
				at prog8.optimizer.StatementOptimizer.after(StatementOptimizer.kt:103)
				at prog8.ast.walk.AstWalker.visit(AstWalker.kt:247)
				at prog8.ast.statements.FunctionCallStatement.accept(AstStatements.kt:547)
				at prog8.ast.walk.AstWalker.visit(AstWalker.kt:232)
				at prog8.ast.statements.Subroutine.accept(AstStatements.kt:670)
				at prog8.ast.walk.AstWalker.visit(AstWalker.kt:218)
				at prog8.ast.statements.Block.accept(AstStatements.kt:67)
				at prog8.ast.walk.AstWalker.visit(AstWalker.kt:194)
				at prog8.ast.Module.accept(AstToplevel.kt:366)
				at prog8.ast.walk.AstWalker.visit(AstWalker.kt:188)
				at prog8.optimizer.ExtensionsKt.optimizeStatements(Extensions.kt:49)
				at prog8.compiler.CompilerKt.optimizeAst(Compiler.kt:270)
				at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:99)
				at prog8.CompilerMainKt.compileMain(CompilerMain.kt:106)
				at prog8.CompilerMainKt.main(CompilerMain.kt:23)
	```
	```
		* internal error *
		Exception in thread "main" prog8.compiler.AssemblyError: There was a problem converting a string to the target machine's char encoding: no lowerScreencode character for '
		' (10)
				at prog8.compiler.target.cpu6502.codegen.AsmGen.encode(AsmGen.kt:254)
				at prog8.compiler.target.cpu6502.codegen.AsmGen.vardecls2asm(AsmGen.kt:393)
				at prog8.compiler.target.cpu6502.codegen.AsmGen.block2asm(AsmGen.kt:198)
				at prog8.compiler.target.cpu6502.codegen.AsmGen.compileToAssembly(AsmGen.kt:62)
				at prog8.compiler.CompilerKt.writeAssembly(Compiler.kt:312)
				at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:105)
				at prog8.CompilerMainKt.compileMain(CompilerMain.kt:106)
				at prog8.CompilerMainKt.main(CompilerMain.kt:23)
	```
* Remarks:
  - `-noopt` irrelevant
  - Using single quotes (character literals) - `txt.print(@'\n')`, `txt.print(@'\r')`, `txt.print(@'\\')` - does yield a proper syntax error, even though characters aren't properly escaped there either
  - I haven't tried everything, so there might be more problematic characters

**Comment by irmen** [comment]
Some improvements are already in place in the development version.
For instance I added a sort-of petscii surrogate for certain not yet mapped characters like the backslash and curly braces. So the errors you got for the backslash are already gone.

I'll look into the others.

**Comment by irmen** [comment]
Unmappable characters in the exception message are now printed in escaped form.

**Comment by meisl** [comment]
Cool! 👍
