### ISSUE TITLE
Bug: float[] initializer with range and no array size given

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#55]
* **Prog8 version**: 7.0
* **Command line**: `java -jar prog8compiler-7.0-all.jar floatArrayInitializerWithRange.p8`
* **Source code**:
  `floatArrayInitializerWithRange.p8`
  ```
  %option enable_floats
  main {
      sub start() {
          float[] cs = 1 to 42 ; values are computed at compile time
          cs[0] = 23 ; keep optimizer from removing it
      }
  } 
  ```
* **Expected**:
  array size of 42 deduced from the given range and the ubytes from it converted to floats, i.e. turned into an explicit array initializer with 42 float constants
* **Actual**:
```
Prog8 compiler v7.0 by Irmen de Jong (irmen@razorvine.net)
This software is licensed under the GNU GPL 3.0, see https://www.gnu.org/licenses/gpl.html

Compiler target: c64. Parsing...
importing 'floatArrayInitializerWithRange'
importing 'syslib' (library)
importing 'math' (library)
importing 'prog8_lib' (library)
Processing for target c64...

* internal error *
Exception in thread "main" prog8.ast.base.FatalAstException: range expressions in vardecls should have been converted into array values during constFolding  VarDecl(name=cs, vartype=VAR, datatype=ARRAY_F, value=RangeExpr(from NumericLiteral(UBYTE:1), to NumericLiteral(UBYTE:42), step NumericLiteral(UBYTE:1), pos=[floatArrayInitializerWithRange.p8: line 4 col 22-29]), pos=[floatArrayInitializerWithRange.p8: line 4 col 9-29])
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:537)
        at prog8.ast.statements.VarDecl.accept(AstStatements.kt:228)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:39)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:253)
        at prog8.ast.statements.Subroutine.accept(AstStatements.kt:643)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:30)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:207)
        at prog8.ast.statements.Block.accept(AstStatements.kt:69)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:14)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:56)
        at prog8.ast.Module.accept(AstToplevel.kt:369)
        at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:10)
        at prog8.compiler.astprocessing.AstChecker.visit(AstChecker.kt:52)
        at prog8.compiler.astprocessing.AstExtensionsKt.checkValid(AstExtensions.kt:14)
        at prog8.compiler.CompilerKt.processAst(Compiler.kt:264)
        at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:98)
        at prog8.CompilerMainKt.compileMain(CompilerMain.kt:115)
        at prog8.CompilerMainKt.main(CompilerMain.kt:21)
```

* **Discussion**:
  - **does NOT happen if array size is given explicitly**
  - **does NOT happen for other array types**
  - the constFolding mentioned in the stack trace happens (or should happen?) in `ConstantIdentifierReplacer.before(VarDecl, Node)` if `decl.dataType == DataType.FLOAT`, around line 117 of `compiler/src/prog8/optimizer/ConstantIdentifierReplacer.kt`
  - in this branch of the `where` range initializers are not covered, whereas they are for the other array types. However: *why is it then not also showing if array size is given explicitly?*

* **Remarks**:
  - again, found this while working on #53
  - there I have added tests for this bug
  - I have to change the relevant AST Node, `RangeExpr` *now*, but not in order to solve this bug (I don't know how) but rather because it depends on `IStringEncoding`, in particular its methods `.toConstantIntegerRange` and `.size`
  - I will do so in the most defensive way possible, but **conflicts are guaranteed if this is worked on in parallel on another branch**
  - apart from that the PR also contains considerable test infrastructure which should actually be used
  - so, if anyone feels inclined to work on this, then it would be best to do so based on what's in the PR, ie. on https://github.com/meisl/prog8/tree/testability_steps_1_2_3_again

**Comment by irmen** [comment]
@meisl  the fix for this problem that I just committed in this branch is only in ConstantIdentifierReplacer.
I also had to adjust the assertions made in the unit test itself though.
I'm considering cherry-picking the fix into my original 7.1 branch to have it there already, before all of the changes in this branch have been sorted out and merged
