### ISSUE TITLE
bug: crash in codegen for uword/ubyte function call argument type mismatch

### ISSUE THREAD

**Issue by irmen** [irmen/prog8#58]
the following code crashes the compiler:
```
        ubyte[] ubs = [1]
        txt.print_uw(ubs[0])
```

crashes with:
```
* internal error *
Exception in thread "main" java.lang.IllegalArgumentException: Failed requirement.
	at prog8.compiler.target.cpu6502.codegen.assignment.AssignmentAsmGen.assignRegisterByte$compiler(AssignmentAsmGen.kt:1369)
	at prog8.compiler.target.cpu6502.codegen.assignment.AssignmentAsmGen.translateNormalAssignment(AssignmentAsmGen.kt:75)
	at prog8.compiler.target.cpu6502.codegen.assignment.AssignmentAsmGen.assignExpressionToRegister$compiler(AssignmentAsmGen.kt:2162)
	at prog8.compiler.target.cpu6502.codegen.assignment.AssignmentAsmGen.assignTypeCastedValue(AssignmentAsmGen.kt:409)
	at prog8.compiler.target.cpu6502.codegen.assignment.AssignmentAsmGen.translateNormalAssignment(AssignmentAsmGen.kt:155)
	at prog8.compiler.target.cpu6502.codegen.AsmGen.translateNormalAssignment$compiler(AsmGen.kt:850)
	at prog8.compiler.target.cpu6502.codegen.FunctionCallAsmGen.argumentViaRegister(FunctionCallAsmGen.kt:341)
	at prog8.compiler.target.cpu6502.codegen.FunctionCallAsmGen.translateFunctionCall$compiler(FunctionCallAsmGen.kt:70)
....
```

**Comment by irmen** [comment]
(fixed in 7.1)
