### ISSUE TITLE
Adding words in memory address causes IllegalArgumentException

### ISSUE THREAD

**Issue by Frosty-J** [irmen/prog8#82]
Hey, Fish. Results below are on version 8.6.2 targeting Commander X16.

**Code:**

```
%zeropage basicsafe
%option no_sysinit
%import textio

main {
  sub start() {
    uword i = 5
    uword w = @(1000 + i)
    txt.print_uw(w)
  }
}
```

**Stack trace:**

```
* internal error *
Exception in thread "main" java.lang.IllegalArgumentException: Failed requirement.
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.assignRegisterByte$codeGenCpu6502(AssignmentAsmGen.kt:1982)
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.assignTypeCastedValue$assignViaExprEval-2(AssignmentAsmGen.kt:855)
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.assignTypeCastedValue(AssignmentAsmGen.kt:873)
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.assignExpression(AssignmentAsmGen.kt:191)
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.translateNormalAssignment(AssignmentAsmGen.kt:169)
        at prog8.codegen.cpu6502.assignment.AssignmentAsmGen.translate(AssignmentAsmGen.kt:27)
        at prog8.codegen.cpu6502.AsmGen.translate$codeGenCpu6502(AsmGen.kt:315)
        at prog8.codegen.cpu6502.ProgramAndVarsGen.translateSubroutine$codeGenCpu6502(ProgramAndVarsGen.kt:339)
        at prog8.codegen.cpu6502.AsmGen.translate$codeGenCpu6502(AsmGen.kt:311)
        at prog8.codegen.cpu6502.ProgramAndVarsGen.block2asm(ProgramAndVarsGen.kt:214)
        at prog8.codegen.cpu6502.ProgramAndVarsGen.generate$codeGenCpu6502(ProgramAndVarsGen.kt:46)
        at prog8.codegen.cpu6502.AsmGen.compileToAssembly(AsmGen.kt:52)
        at prog8.compiler.CompilerKt.createAssemblyAndAssemble(Compiler.kt:408)
        at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:118)
        at prog8.CompilerMainKt.compileMain(CompilerMain.kt:202)
        at prog8.CompilerMainKt.main(CompilerMain.kt:27)
```

**Comment by irmen** [comment]
The bug is in the *assignment* of the byte value to the w variable which is a word.
This should not crash the compiler ofcourse.
