### ISSUE TITLE
How to use `sort`?   [compiler crash]

### ISSUE THREAD

**Issue by megagrump** [irmen/prog8#95]
```
%zeropage basicsafe

main {
	ubyte[5] cards = [ 14, 6, 29, 16, 3 ]

	sub start() {
		sort(cards)
	}
}
```
```
$ java -jar ../prog8compiler-8.9-all.jar -target cx16 main.p8

Prog8 compiler v8.9 by Irmen de Jong (irmen@razorvine.net)
This software is licensed under the GNU GPL 3.0, see https://www.gnu.org/licenses/gpl.html

Compilation target: cx16
 importing 'main'  (from main.p8)[0K
 importing 'syslib'  (from library:/prog8lib/cx16/syslib.p8)[0K
 importing 'math'  (from library:/prog8lib/math.p8)[0K
 importing 'prog8_lib'  (from library:/prog8lib/prog8_lib.p8)[0K
Parsed main.p8[0K
Analyzing code...
Optimizing...

[91m
* internal error *
[0mException in thread "main" java.lang.NullPointerException
	at prog8.optimizer.Inliner$DetermineInlineSubs.makeFullyScoped(Inliner.kt:133)
	at prog8.optimizer.Inliner$DetermineInlineSubs.visit(Inliner.kt:96)
	at prog8.ast.statements.Subroutine.accept(AstStatements.kt:739)
	at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:35)
	at prog8.optimizer.Inliner$DetermineInlineSubs.visit(Inliner.kt:21)
	at prog8.ast.statements.Block.accept(AstStatements.kt:90)
	at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:14)
	at prog8.optimizer.Inliner$DetermineInlineSubs.visit(Inliner.kt:21)
	at prog8.ast.Module.accept(AstToplevel.kt:319)
	at prog8.ast.walk.IAstVisitor$DefaultImpls.visit(IAstVisitor.kt:10)
	at prog8.optimizer.Inliner$DetermineInlineSubs.visit(Inliner.kt:21)
	at prog8.optimizer.Inliner$DetermineInlineSubs.<init>(Inliner.kt:25)
	at prog8.optimizer.Inliner.before(Inliner.kt:171)
	at prog8.ast.walk.AstWalker.visit(AstWalker.kt:215)
	at prog8.optimizer.ExtensionsKt.inlineSubroutines(Extensions.kt:59)
	at prog8.compiler.CompilerKt.optimizeAst(Compiler.kt:365)
	at prog8.compiler.CompilerKt.compileProgram(Compiler.kt:99)
	at prog8.CompilerMainKt.compileMain(CompilerMain.kt:199)
	at prog8.CompilerMainKt.main(CompilerMain.kt:27)```

**Comment by irmen** [comment]
Why do people always seem to find such issues RIGHT after the release was made?   :laughing: 

Anyway, this is clearly a bug in the optimizer, the compiler should never crash like this. I'll investigate.

**Comment by irmen** [comment]
- this also occurs for `reverse()`
- seems to be caused by not actually using the array itself beside sort() or reverse().  If you add more code that uses the array variable, the error disappears.
